---

name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest  # Updated to the latest Ubuntu version
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Latest stable version
        with:
          username: ${{ secrets.DOCKERHUB_USER }} #updated user
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout repository
        uses: actions/checkout@v4  # Latest stable version
        
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
        
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
